### ISSUE TITLE
Should we remove the unsupported minors?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Msmq.WireCompatTests#2]
How about we keep 3.3,4.7 and 5.2 and remove the other unsupported minors to clean up this a bit?

cc @Particular/nservicebus-maintainers @SimonCropp

**Comment by timbussmann** [comment]
if it makes maintenance of this repo easier, I'm 👍

**Comment by danielmarbach** [comment]
Took the liberty of merging @SimonCropp PR. Will try to address callbacks issue
