### ISSUE TITLE
Build is failing with vierd inspection errors

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Msmq.WireCompatTests#4]
see https://builds.particular.net/viewType.html?buildTypeId=NServiceBus_Transports_NServiceBusMsmq_NServiceBusMsmqWireCompatTests&branch_NServiceBus_Transports_NServiceBusMsmqWireCompatTests=%3Cdefault%3E&tab=buildTypeStatusDiv

Is started for no reason sometime between dec 13 and jan 18.

I suspect updated inspection runner? @gbiellem idea?

**Comment by gbiellem** [comment]
@andreasohlund  could be a problem with the resharper command line tool.   Between green and red builds it was switched to a newer version -> https://builds.particular.net/admin/editRunType.html?id=buildType:NServiceBus_Transports_NServiceBusMsmq_NServiceBusMsmqWireCompatTests&runnerId=RUNNER_204

The change happened in the build template so at the build config level it looked like nothing had changed.  We can test this by reverting this build to older version of the CLT

**Comment by andreasohlund** [comment]
Downgrading to teamcity.tool.jetbrains.resharper-clt.2016.2.20160913.100041 fixed the issue

**Comment by andreasohlund** [comment]
Is there some inspection settings in the repo that we need to update perhaps?

**Comment by gbiellem** [comment]
Resharper 2016.3 added new inspections and the new CLT reflects that.  The failed builds seem to list only two inspections repeatedly, so my guess is they are new ones and the default is to treat them as errors.

**Comment by andreasohlund** [comment]
Got, I'll upgrade to 2016.3 and see if it fails locally

**Comment by andreasohlund** [comment]
Everything is green locally with 2016.3.1 :(

**Comment by gbiellem** [comment]
So after wasting a lot of time testing and trying to solve this I went looking on the JetBrains issue tracker.  
It's a known bug with InspectCode.exe -> https://youtrack.jetbrains.com/issue/RSRP-462401 

Next time I'll check the bug list first 😥

**Comment by andreasohlund** [comment]
I've forced the build to use the previous runner so we're all good for now

**Comment by gbiellem** [comment]
Tried the new inspectcode.exe  released 26th January 2017 - Still not fixed

**Comment by SimonCropp** [comment]
no longer inspecting
